config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :new, :edit, :update, :show] do
    resource :password,controller: "clearance/passwords", only: [:create, :edit, :update] 
  end

  resources :listings, controller: "listings" do 
    resources :reservations, controller: "reservations" do  
    end 
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/mylistings" => "listings#mylistings", as: "my_listings"
  get "/your_reservations" => "reservations#your_reservations", as: "your_reservations"
  get "/payment" => "braintree#new", as: "payment"
  post "/payment/checkout"=> "braintree#checkout", as: "payment_checkout"
end


# session has no :id therefore it is just park under resource 
# resources provides the 7 restful routes 

# resource: book || session || listing || user
# 7 restful routes

# new => a form to a new resource
# create => sending information from new form to create 
# index => show all the resource
# show => show one particular resource
# edit => to show a form to edit a resource
# update => sending information from edit form to edit 
# resource

# delete => to delete a resource

#redirect_to sign_in_path relates to /sign_in 

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
    @client_token = Braintree::ClientToken.generate
    @reservation = Reservation.find(params[:id])
  end

  def checkout
  	@reservation = Reservation.find(params[:id]) 
    @listing = @reservation.listing 
    @user = @reservation.user
    @price = @listing.price_cents 
    @numberofdays = (@reservation.arriving_date...@reservation.leaving_date).count 
    @total_price = @price * @numberofdays
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
    result = Braintree::Transaction.sale(
     :amount => @total_price, 
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )

    if result.success?
      @reservation.update(total_price_cents: @total_price, payment_status:1) 
      redirect_to your_reservations_path, :flash => { :success => "Transaction successful!" }
      SendReservationEmailJob.set(wait: 20.seconds).perform_later(@user, @listing.user, @reservation)  
    else
      redirect_to your_reservations_path, :flash => { :error => "Transaction failed. Please try again." }
    end
  end

end

app/views/braintree/new.html.erb
<div class="demo-frame">
  <%= form_for :checkout_form, url: payment_checkout_path(id: @reservation.id), html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  var authorization = '<%= @client_token %>';

// need to put back to braintree.js 

  var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    console.log(clientErr)
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt',
        'font-family': 'courier, monospace',
        'font-weight': 'lighter',
        'color': '#ccc'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      },
      ':focus': {
        'color': 'black'
      },
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});

</script>