config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :new, :edit, :update, :show] do
    resource :password,controller: "clearance/passwords", only: [:create, :edit, :update] 
  end

  resources :listings, controller: "listings" do 
    resources :reservations, controller: "reservations" do  
    end 
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/mylistings" => "listings#mylistings", as: "my_listings"
  get "/your_reservations" => "reservations#your_reservations", as: "your_reservations"
  get "/payment" => "braintree#new", as: "payment"
  post "/payment/checkout"=> "braintree#checkout", as: "payment_checkout"
end


# session has no :id therefore it is just park under resource 
# resources provides the 7 restful routes 

# resource: book || session || listing || user
# 7 restful routes

# new => a form to a new resource
# create => sending information from new form to create 
# index => show all the resource
# show => show one particular resource
# edit => to show a form to edit a resource
# update => sending information from edit form to edit 
# resource

# delete => to delete a resource

#redirect_to sign_in_path relates to /sign_in 

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user 
  has_many :reservations, dependent: :destroy 
  enum verified: [:false, :true]
  mount_uploaders :listing_images, ImageUploader
  validates :listing_images, file_size: { less_than: 3.megabytes }
  monetize :price_cents
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:edit, :update, :show, :destroy]

  # Path = listings_path 
  # GET /listings 
  def index
    @listings = Listing.all.order(created_at: :desc).where(verified:0) 
  end

  # Path = new_listing_path 
  # GET /listings/new  
  def new
    @listing = Listing.new 
  end

  # POST /listings 
  def create
      @listing = current_user.listings.new(listings_params)
      if @listing.save
          redirect_to listing_path 
      else 
        render "new"
      end
  end

  # Path = edit_listing_path 
  # GET /listing/:id/edit 
  def edit
  end


  # Path = edit_listing_path 
  # PATCH /listing/:id 
  def update 
    if @listing.update_attributes(listings_params)
        redirect_to listing_path 
    else 
        render "edit"
    end 
  end 

  # Path = listing_path 
  # GET /listings/:id  
  def show
    @listing = Listing.find(params[:id])
  end 

  # Path = my_listings_path
  # GET /mylistings 
  def mylistings
    @listings = current_user.listings
    render "index"
  end

  # Path = listing_path 
  # DELETE /listings/:id  
  def destroy
    if @listing.destroy 
      redirect_to listings_path
    else 
      redirect_to @listing  
    end 
  end

  # def verify 
  #   if current_user.admin?
  #     @verify_listings = Listing.find_by_id(params[:id]).update(verified:1)
  #     redirect_to @verified_listings 
  #   end 
  # end 

private 
  def listings_params 
    params.require(:listing).permit( 
      :name, 
      :place_type, 
      :room_number, 
      :bed_number, 
      :guest_number, 
      :country, 
      :state, 
      :city, 
      :zipcode, 
      :description, 
      :address, 
      :price_cents,
      :price_currency, 
      {listing_images: []})
  end

# Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
  end
end 

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing do |form| %>

<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :place_type %>
  <%= form.text_field :place_type, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :description %>
  <%= form.text_area :description, type: 'text' %>
</div>

<div class="number-field">
  <%= form.label :bed_number %>
  <%= form.number_field :bed_number, type: 'number' %>
</div>

<div class="number-field">
  <%= form.label :guest_number %>
  <%= form.text_field :guest_number, type: 'number' %>
</div>

<div class="text-field">
  <%= form.label :country %>
  <%= form.text_field :country, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :state %>
  <%= form.text_field :state, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :city %>
  <%= form.text_field :city, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :zipcode %>
  <%= form.text_field :zipcode, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :address %>
  <%= form.text_field :address, type: 'text' %>
</div>

<div class="number-field">
  <%= form.label :price %>
  <%= form.number_field :price_cents, type: 'number', step: 0.01 %> <br/> 
</div>

<div class="image-field">
  <%= form.label :images %> 
  <%= form.file_field :listing_images, multiple: true %>
</div> 

<%= form.submit %> 

<% end %> 

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render partial: "form" %>

<div class="other-links">
	<%= link_to "New Listing", new_listing_path %> <br/>
	<%= link_to "Show My Listings", my_listings_path %> 
</div>

app/views/listings/index.html.erb
<ul> 
<% @listings.each do |l| %>
	<li> <%= link_to l.name, listing_path(l) %> </li>  
	<%= l.description %> 
	<br/> 
	
	<% if l.listing_images != nil %> 
		<% l.listing_images.each do |images| %> 
			<img src= "<%= images.bigthumb.url %>" >		
		<% end %> 
	<% end %> 
	<br/> 	

<% end %>  
</ul>

<div class="other-links">
	<%= button_to "Create New Listing", new_listing_path, method: :get %> <br/>
	<%= button_to "Show My Listings", my_listings_path, method: :get %> <br/> 
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render partial: "form" %> 

<div class="other-links">
	<%= link_to "Show My Listings", my_listings_path %> 
</div>






    

app/views/listings/show.html.erb
<h1>Show My Listing</h1>

<ul> 
	<li> Listing Name: <%= @listing.name %> </li> 
	<li> Description: <%= @listing.description %> </li>  
	<li> Price: <%= humanized_money_with_symbol @listing.price_cents %> </li> 

	<% if @listing.listing_images != nil %> 
		<% @listing.listing_images.each do |images| %> 
				<img src= "<%= images.bigthumb.url %>" >		
		<% end %>		
	<% end %>		 
</ul>

<%= form_tag new_listing_reservation_path(@listing.id), method: :get do %>
    <input type="submit" value="Request to book?">
<% end %>

<br/>

<% if current_user == @listing.user %>
	<%= button_to "Edit", edit_listing_path, method: :get %>
	<%= button_to "Delete", listing_path, method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>