config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :new, :edit, :update, :show] do
    resource :password,controller: "clearance/passwords", only: [:create, :edit, :update] 
  end

  resources :listings, controller: "listings" do 
    resources :reservations, controller: "reservations" do  
    end 
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/mylistings" => "listings#mylistings", as: "my_listings"
  get "/your_reservations" => "reservations#your_reservations", as: "your_reservations"
  get "/payment" => "braintree#new", as: "payment"
  post "/payment/checkout"=> "braintree#checkout", as: "payment_checkout"
end


# session has no :id therefore it is just park under resource 
# resources provides the 7 restful routes 

# resource: book || session || listing || user
# 7 restful routes

# new => a form to a new resource
# create => sending information from new form to create 
# index => show all the resource
# show => show one particular resource
# edit => to show a form to edit a resource
# update => sending information from edit form to edit 
# resource

# delete => to delete a resource

#redirect_to sign_in_path relates to /sign_in 

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :listings, dependent: :destroy 
  has_many :reservations, dependent: :destroy 
  enum role: [:customer, :moderator, :superadmin]
  mount_uploader :image, ImageUploader
  validates :image, file_size: { less_than: 1.megabytes }
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
  end

  def create
    @user = user_from_params
    if @user.save
      sign_in @user
      redirect_to root_url 
    else
      render template: "users/new"
    end
  end

  def show 
    @user = User.find(params[:id])
  end 

  def edit 
    @user = User.find(params[:id])
  end 

  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(update_user_params)
    redirect_to root_url
    else 
      render template: "users/edit"
      flash[:unsuccessful_update] = "Please try again"
    end 
  end 

  private
  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def update_user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :birthday, :image)
  end 

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
	  first_name = user_params.delete(:first_name)
	  last_name = user_params.delete(:last_name)
	  birthday = user_params.delete(:birthday)   
    role = user_params.delete(:role)
    image = user_params.delete(:image)

  Clearance.configuration.user_model.new(user_params).tap do |user|
	   user.email = email
	   user.password = password
	   user.first_name = first_name
	   user.last_name = last_name
	   user.birthday = birthday
     user.role = role 
     user.image = image 
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/views/users/_form.html.erb
<div class="row">  
     <div class="col-md-3">
       <ul class= "sidebar-list">

   </div>    
      </ul>    
       <div class="col-md-7 text-center">

      <div class="panel panel-default">

          <div class="panel-heading">Edit your Profile</div> </br>

               

               <div class="panel-body">

                   <div class="container">
   
                 <div class="form-group">First Name
   
                 <%= form.text_field :first_name, autofocus: true, class: "form-control", placeholder: "First Name" %>
   
                 </div>

                 <div class="form-group">First Name
   
                 <%= form.text_field :last_name, autofocus: true, class: "form-control", placeholder: "Last Name" %>
   
                 </div>
   
                 <div class="form-group">Email
   
                <%= form.email_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
   
                 </div>

                  <div class="row">
   
                   <div class="col-md-4">
   
                    <div class="form-group">
   
                      <span class="btn btn-default btn-file"> 

                      Upload your profile picture </span> <%= form.file_field :image %>
   
                      </span>
   
                  </div>
   
                  </div>  
   
                  </div>

                 <div class="form-group"> Birthday
                 <%=form.date_field :birthday, class: "form-control", placeholder: "BD" %>
                 </div>

                 </br>
                 <div class="form-group"> Password 
                   <%= form.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Enter new password if you wish to change" %>
                 </div>
                 <div class="actions">
                   <%= form.submit "Save", class: "btn btn-primary" %>
                 </div>
       </div>
   </div>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
    	<%= render partial: '/users/form', object: form %>
 <% end %>

app/views/users/new.html.erb
<h1>Create your profile</h1>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to (".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>My Profile</h1>

<ul> 
	<li> <%= @listing.name %> <br/> 
	<%= @listing.description %> </li> <br/>     

	<% if @listing.listing_images != nil %> 
		<% @listing.listing_images.each do |images| %> 
				<img src= "<%= images.bigthumb.url %>" >		
		<% end %>		
	<% end %>		 
</ul>

<% if current_user == @listing.user %>
	<%= button_to "Edit", edit_listing_path, method: :get %>
	<%= button_to "Delete", listing_path, method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>