config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :new, :edit, :update, :show] do
    resource :password,controller: "clearance/passwords", only: [:create, :edit, :update] 
  end

  resources :listings, controller: "listings" do 
    resources :reservations, controller: "reservations" do  
    end 
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/mylistings" => "listings#mylistings", as: "my_listings"
  get "/your_reservations" => "reservations#your_reservations", as: "your_reservations"
  get "/payment" => "braintree#new", as: "payment"
  post "/payment/checkout"=> "braintree#checkout", as: "payment_checkout"
end


# session has no :id therefore it is just park under resource 
# resources provides the 7 restful routes 

# resource: book || session || listing || user
# 7 restful routes

# new => a form to a new resource
# create => sending information from new form to create 
# index => show all the resource
# show => show one particular resource
# edit => to show a form to edit a resource
# update => sending information from edit form to edit 
# resource

# delete => to delete a resource

#redirect_to sign_in_path relates to /sign_in 

app/views/layouts/_navbar.html.erb
<!-- Company Logo -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-image">
    <img src="https://cdn.dribbble.com/users/204536/screenshots/1247790/logo_1x.jpg" width="50" height="40" alt="">
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!-- Home page link -->
        <li class="nav-item active">
          <a class="nav-link" href="/"> Home <span class="sr-only"></span></a>
        </li>

        <!-- User link -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">User</a>
        <!-- User dropdown menu -->
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if signed_in? -%>
                <a class="dropdown-item"> <%= link_to "Sign Out", sign_out_path, method: :delete, data: { confirm: 'Are you sure?'} %> </a>
                <a class="dropdown-item" href="/users/<%=current_user.id%>/edit"> Edit Profile </a> 
                <% else %> 
                <a class="dropdown-item"><%= link_to "Sign In", sign_in_path %> </a> 
                <a class="dropdown-item"><%= link_to "Sign Up", sign_up_path %> </a> 
                <% end %> 
            </div>  
        </li>
        <!-- Listing & Reservations -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Listings </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/listings">All Listings</a>
            <a class="dropdown-item" href="#">Your Listings</a>
          <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>

        </li>
        <!-- Extra Link -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Reservations </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/your_reservations"> Your Reservations </a>
          <div class="dropdown-divider"></div>
            <a class="dropdown-item disabled" href="#">Disabled link</a>
          </div>
        </li>
      </ul>
      <!-- Search Bar -->
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>    
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <!-- Load bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <!-- Load the braintree client component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
  <!-- Load the Hosted Fields component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <!-- Load jquery -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <!-- Load jquery ujs -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.js"></script>
  <!-- Load jquery popper -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <!-- Load bootstrap own JS plugins -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  <!-- Load viewport for multiple devices -->
  <meta name="viewport" content="width=device-width, initial-scale=1">  
  <!-- Link to google font-->
  <link href="https://fonts.googleapis.com/css?family=Tajawal" rel="stylesheet">
</head>
<body>

  <div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%=h value %></div>
  <% end %>
  </div>

  <%= render "layouts/navbar" %> 

  <%= yield %>

</body>
</html>